// src/components/encode/steps/OutputsStep.tsx
import React from "react";
import { useFormContext, Controller } from "react-hook-form";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

const formats = ["PDF", "Rapport numérique", "Certification numérique", "Financement / Versement bancaire", "Mise en relation directe", "Code source / Prototype"];

export default function OutputsStep() {
  const { control } = useFormContext();

  return (
    <section className="space-y-6">
      <div className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-gray-100 dark:border-gray-700 shadow-sm space-y-4">
        <h3 className="text-lg font-bold text-gray-900 dark:text-gray-100 border-b pb-2">
          Outputs (Livrables et Résultats Directs)
        </h3>
        <p className="text-sm text-gray-500">
          Définissez les délivrables ou documents finaux générés pour l’usager à la fin de la prestation du service.
        </p>

        <Controller
          name="outputs.outputs"
          control={control}
          defaultValue={[{ name: "Rapport de diagnostic de maturité numérique", format: "PDF", autoGenerated: true, validityMonths: 12 }]}
          render={({ field }) => {
            const list = field.value || [];
            const addOutput = () => field.onChange([...list, { name: "", format: "Rapport numérique", autoGenerated: false, validityMonths: 0 }]);
            const updateOutput = (idx: number, key: string, val: any) => {
              const updated = [...list];
              updated[idx] = { ...updated[idx], [key]: val };
              field.onChange(updated);
            };
            const removeOutput = (idx: number) => {
              field.onChange(list.filter((_: any, i: number) => i !== idx));
            };

            return (
              <div className="space-y-4">
                {list.map((output: any, idx: number) => (
                  <div key={idx} className="bg-gray-50 dark:bg-gray-900 p-4 rounded-xl border border-gray-200/50 dark:border-gray-800 space-y-3">
                    <div className="flex justify-between items-center">
                      <span className="text-xs font-bold text-gray-400">OUTPUT / LIVRABLE {idx + 1}</span>
                      <button
                        type="button"
                        onClick={() => removeOutput(idx)}
                        className="text-xs text-red-500 hover:underline"
                      >
                        Supprimer
                      </button>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      {/* Name */}
                      <div>
                        <label className="block text-xs font-semibold mb-1 text-gray-500">Nom de l'output</label>
                        <Input
                          value={output.name}
                          onChange={(e) => updateOutput(idx, "name", e.target.value)}
                          placeholder="ex. Prototype IA validé (PoC)"
                        />
                      </div>

                      {/* Format */}
                      <div>
                        <label className="block text-xs font-semibold mb-1 text-gray-500">Format de délivrance</label>
                        <Select
                          onValueChange={(val: string) => updateOutput(idx, "format", val)}
                          defaultValue={output.format}
                        >
                          <SelectTrigger className="w-full">
                            <SelectValue placeholder="Sélectionnez le format" />
                          </SelectTrigger>
                          <SelectContent>
                            {formats.map((f) => (
                              <SelectItem key={f} value={f}>{f}</SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>

                      {/* Validity months */}
                      <div>
                        <label className="block text-xs font-semibold mb-1 text-gray-500">Validité sémantique (en mois - 0 si illimité)</label>
                        <Input
                          type="number"
                          value={output.validityMonths || ""}
                          onChange={(e) => updateOutput(idx, "validityMonths", parseInt(e.target.value) || 0)}
                          placeholder="ex. 12"
                        />
                      </div>

                      {/* Auto generated check */}
                      <div className="flex items-center space-x-2 pt-5">
                        <Checkbox
                          checked={output.autoGenerated}
                          onCheckedChange={(checked: any) => updateOutput(idx, "autoGenerated", !!checked)}
                        />
                        <span className="text-xs text-gray-700 dark:text-gray-200 font-semibold">Généré automatiquement par le système</span>
                      </div>
                    </div>
                  </div>
                ))}
                <button
                  type="button"
                  onClick={addOutput}
                  className="text-xs px-3 py-1.5 bg-gray-100 dark:bg-gray-700 rounded text-gray-700 dark:text-gray-200 font-semibold transition hover:bg-gray-200 dark:hover:bg-gray-600"
                >
                  + Ajouter un output
                </button>
              </div>
            );
          }}
        />
      </div>
    </section>
  );
}
