import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppProvider from "./AppProvider";
import Sidebar from "../components/Sidebar";
import Topbar from "../components/Topbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
        <AppProvider>
          <div className="flex min-h-screen bg-background text-text">
            <React.Suspense fallback={<div className="w-64 bg-surface border-r border-muted/20 h-screen sticky top-0" />}>
              <Sidebar />
            </React.Suspense>
            <main className="flex-1 flex flex-col overflow-y-auto p-6">
              <Topbar />
              <div className="flex-1 mt-4">{children}</div>
            </main>
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
