// src/lib/schema/cpsv.ts
import { z } from "zod";

// Enumerations
const statusEnum = ["Draft", "Review", "Approved", "Published", "Archived"] as const;
const languageEnum = ["fr", "nl", "de", "en"] as const;
const themeEnum = ["IA", "Industrie 4.0", "Cybersécurité", "Financement", "Export", "Énergie", "Circularité", "Innovation", "Formation", "Smart Region"] as const;
const TRLenum = ["TRL 1 - Principes de base", "TRL 2 - Concept technologique", "TRL 3 - Preuve de concept", "TRL 4 - Validation en labo", "TRL 5 - Validation en environnement représentatif", "TRL 6 - Démonstration", "TRL 7 - Prototype en environnement opérationnel", "TRL 8 - Système qualifié", "TRL 9 - Déploiement commercial"] as const;
const maturityEnum = ["Beginner", "Intermediate", "Advanced", "Expert"] as const;

// 1. Informations générales
export const generalInfoSchema = z.object({
  name: z.string().min(1, "Le nom du service est obligatoire"),
  uri: z.string().url().optional(),
  shortDescription: z.string().min(1, "La description courte est obligatoire").max(300, "Maximum 300 caractères"),
  description: z.string().optional(),
  status: z.enum(statusEnum).default("Draft"),
  language: z.enum(languageEnum).default("fr"),
  version: z.string().default("1.0.0"),
  themes: z.array(z.enum(themeEnum)).optional(),
  tags: z.array(z.string()).optional(),
  s3Domain: z.string().optional(),
  priority: z.string().optional(),
});

// 2. Description métier
export const businessDescriptionSchema = z.object({
  objective: z.string().optional(),
  problemSolved: z.string().optional(),
  valueAdded: z.string().optional(),
  targetDigitalMaturity: z.enum(maturityEnum).optional(),
  targetTRL: z.enum(TRLenum).optional(),
  expectedTransformation: z.string().optional(),
});

// 3. Organisations fournisseuses
export const providersSchema = z.object({
  primaryProvider: z.string().min(1, "L'organisation principale est obligatoire"),
  partners: z.array(z.string()).optional(),
  contactName: z.string().optional(),
  contactEmail: z.string().email("Format email invalide").optional().or(z.literal("")),
  contactPhone: z.string().optional(),
  website: z.string().url("Format URL invalide").optional().or(z.literal("")),
});

// 4. Bénéficiaires / Target Audiences
export const beneficiariesSchema = z.object({
  orgTypes: z.array(z.string()).optional(),
  companySizes: z.array(z.string()).optional(),
  sectors: z.array(z.string()).optional(),
  territories: z.array(z.string()).optional(),
  digitalMaturity: z.array(z.enum(maturityEnum)).optional(),
  s3Priorities: z.array(z.string()).optional(),
  primaryTarget: z.string().optional(),
});

// 5. Business Events / Life Events
export const eventsSchema = z.object({
  businessEvents: z.array(z.string()).optional(),
  lifeEvents: z.array(z.string()).optional(),
});

// 6. Conditions / Contraintes / Eligibilité
export const conditionsSchema = z.object({
  rules: z.array(z.string()).optional(),
  operator: z.enum(["AND", "OR", "NOT"]).default("AND"),
  hasValidBce: z.boolean().default(true),
  isWalloon: z.boolean().default(true),
});

// 7. Inputs / Evidence / Documents requis
export const documentsSchema = z.object({
  requiredDocs: z.array(
    z.object({
      name: z.string(),
      format: z.string().optional(),
      isMandatory: z.boolean().default(false),
      expirationMonths: z.number().optional(),
    })
  ).optional(),
});

// 8. Channels d'accès
export const channelsSchema = z.object({
  primaryChannel: z.string().optional(),
  allChannels: z.array(z.string()).optional(),
  url: z.string().url("Format URL invalide").optional().or(z.literal("")),
  sla: z.string().optional(),
  availability: z.string().optional(),
  location: z.string().optional(),
});

// 9. Outputs
export const outputsSchema = z.object({
  outputs: z.array(
    z.object({
      name: z.string(),
      format: z.string().optional(),
      autoGenerated: z.boolean().default(false),
      validityMonths: z.number().optional(),
    })
  ).optional(),
});

// 10. Outcomes
export const outcomesSchema = z.object({
  outcomes: z.array(
    z.object({
      type: z.string(),
      horizon: z.string().optional(),
      associatedKpi: z.string().optional(),
      measurementMode: z.string().optional(),
    })
  ).optional(),
});

// 11. Impacts territoriaux
export const impactsSchema = z.object({
  jobsCreated: z.number().min(0).optional(),
  carbonImpact: z.number().min(0).max(100).optional(), // 0 to 100 scoring
  sovereignty: z.number().min(0).max(100).optional(),
  resilience: z.number().min(0).max(100).optional(),
  competitiveness: z.number().min(0).max(100).optional(),
});

// 12. Ressources nécessaires
export const resourcesSchema = z.object({
  resourcesList: z.array(
    z.object({
      type: z.string(),
      isMandatory: z.boolean().default(true),
      isShareable: z.boolean().default(false),
      costEstimate: z.number().optional(),
      availability: z.string().optional(),
    })
  ).optional(),
});

// 13. Services liés
export const relatedServicesSchema = z.object({
  prerequisites: z.array(z.string()).optional(),
  complementary: z.array(z.string()).optional(),
  recommendedNext: z.array(z.string()).optional(),
  successors: z.array(z.string()).optional(),
});

// 14. Parcours client
export const journeySchema = z.object({
  phases: z.array(z.string()).optional(),
  journeyTimeline: z.string().optional(),
});

// 15. Indicateurs / KPI
export const kpisSchema = z.object({
  kpisList: z.array(
    z.object({
      name: z.string(),
      targetValue: z.number().optional(),
      currentValue: z.number().optional(),
      autoMeasure: z.boolean().default(false),
    })
  ).optional(),
});

// 16. Interopérabilité & métadonnées
export const interopSchema = z.object({
  uri: z.string().url().optional(),
  semicVocab: z.string().default("http://data.europa.eu/m8g/"),
  ngsiLdTags: z.array(z.string()).optional(),
  externalId: z.string().optional(),
  linkedDatasets: z.array(z.string()).optional(),
  cpsvVersion: z.string().default("3.0.0"),
});

// 17. Publication & gouvernance
export const publicationSchema = z.object({
  workflowStatus: z.enum(statusEnum).default("Draft"),
  businessValidator: z.string().optional(),
  technicalValidator: z.string().optional(),
  dataGovernanceNotes: z.string().optional(),
});

// Coûts schema
export const costsSchema = z.object({
  free: z.boolean().default(true),
  amount: z.number().optional(),
  currency: z.string().default("EUR"),
  subsidized: z.boolean().default(false),
  description: z.string().optional(),
});

// Complete CPSV-AP schema with 17 steps
export const cpsvSchema = z.object({
  generalInfo: generalInfoSchema,
  businessDescription: businessDescriptionSchema,
  providers: providersSchema,
  beneficiaries: beneficiariesSchema,
  events: eventsSchema,
  conditions: conditionsSchema,
  documents: documentsSchema,
  channels: channelsSchema,
  outputs: outputsSchema,
  outcomes: outcomesSchema,
  impacts: impactsSchema,
  resources: resourcesSchema,
  relatedServices: relatedServicesSchema,
  costs: costsSchema.optional(),
  journey: journeySchema,
  kpis: kpisSchema,
  interop: interopSchema,
  publication: publicationSchema,
});

export type CpsvService = z.infer<typeof cpsvSchema>;
